from __future__ import annotations

import argparse
import json
import logging
import sys
from pathlib import Path
from typing import Dict, List, Sequence, Tuple

import numpy as np
import pandas as pd


TARGET_COL_DEFAULT: str = "PM2.5"


def setup_logging(level: str) -> None:
    """Configure logging."""
    logging.basicConfig(
        level=getattr(logging, level.upper(), logging.INFO),
        format="%(asctime)s | %(levelname)s | %(message)s",
    )


def load_parquet(path: Path) -> pd.DataFrame:
    """Load parquet."""
    if not path.exists():
        raise FileNotFoundError(f"Missing parquet: {path}")
    return pd.read_parquet(path)


def select_feature_columns(df: pd.DataFrame, target_col: str) -> List[str]:
    """Select numeric feature columns."""
    exclude = {"station", "timestamp", "source_file", "source_sheet", target_col}
    cols: List[str] = []
    for c in df.columns:
        if c in exclude:
            continue
        if pd.api.types.is_numeric_dtype(df[c]):
            cols.append(c)
    return cols


def split_xy(df: pd.DataFrame, feature_cols: Sequence[str], target_col: str) -> Tuple[np.ndarray, np.ndarray]:
    """Create arrays."""
    x = df.loc[:, list(feature_cols)].to_numpy(dtype=np.float32, copy=False)
    y = df.loc[:, target_col].to_numpy(dtype=np.float32, copy=False)
    return x, y


def load_sklearn_bundle(path: Path) -> Tuple[object, List[str], str]:
    """Load sklearn joblib bundle."""
    import joblib

    bundle = joblib.load(path)
    return bundle["model"], list(bundle["feature_cols"]), str(bundle["target"])


def load_xgb(model_path: Path, meta_path: Path) -> Tuple[object, List[str], str]:
    """Load xgboost model + meta."""
    import xgboost as xgb

    booster = xgb.Booster()
    booster.load_model(model_path)
    meta = json.loads(meta_path.read_text(encoding="utf-8"))
    return booster, list(meta["feature_cols"]), str(meta["target"])


def main() -> int:
    """Generate quick plots for report: prediction vs actual and scatter."""
    parser = argparse.ArgumentParser(description="Generate prediction-vs-actual plots for trained models.")
    parser.add_argument("--test", type=str, default=str(Path("artifacts") / "features_test.parquet"))
    parser.add_argument("--models-dir", type=str, default=str(Path("artifacts") / "models"))
    parser.add_argument("--out-dir", type=str, default=str(Path("artifacts") / "plots"))
    parser.add_argument("--target", type=str, default=TARGET_COL_DEFAULT)
    parser.add_argument("--log-level", type=str, default="INFO")
    parser.add_argument("--max-points", type=int, default=2000, help="Max points per station for plotting.")
    args = parser.parse_args()

    setup_logging(args.log_level)

    try:
        import matplotlib.pyplot as plt
    except Exception as e:
        logging.error("Missing matplotlib. Install requirements_ml.txt. err=%s", e)
        return 4

    test_df = load_parquet(Path(args.test).resolve()).sort_values(["station", "timestamp"]).reset_index(drop=True)
    target_col = str(args.target)
    models_dir = Path(args.models_dir).resolve()
    out_dir = Path(args.out_dir).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    if target_col not in test_df.columns:
        logging.error("Target missing: %s", target_col)
        return 2

    # Load available models.
    models: Dict[str, Tuple[str, object, List[str]]] = {}
    ridge_path = models_dir / "ridge.joblib"
    rf_path = models_dir / "random_forest.joblib"
    xgb_path = models_dir / "xgb.json"
    xgb_meta = models_dir / "xgb_meta.json"

    if ridge_path.exists():
        m, feats, _ = load_sklearn_bundle(ridge_path)
        models["ridge"] = ("sklearn", m, feats)
    if rf_path.exists():
        m, feats, _ = load_sklearn_bundle(rf_path)
        models["random_forest"] = ("sklearn", m, feats)
    if xgb_path.exists() and xgb_meta.exists():
        try:
            booster, feats, _ = load_xgb(xgb_path, xgb_meta)
        except Exception as e:
            logging.warning("Failed loading xgb: %s", e)
        else:
            models["xgboost"] = ("xgb", booster, feats)

    if not models:
        # In the newer pipeline, models may live in `artifacts/` (per-station) and
        # plots are generated by `5_evaluate_and_plot.py`. We keep this script as a
        # legacy helper; if no models exist in `models_dir`, do not fail hard.
        logging.warning("No models found in %s. Skipping legacy plotting.", models_dir)
        return 0

    # Plot per station, using a capped window to keep files manageable.
    for station, sdf in test_df.groupby("station", sort=False):
        sdf = sdf.dropna(subset=[target_col]).copy()
        if sdf.empty:
            continue
        sdf = sdf.tail(int(args.max_points))

        # Build predictions for each model (dropping NaNs per model features).
        preds: Dict[str, np.ndarray] = {}
        y_true = sdf[target_col].to_numpy(dtype=np.float32, copy=False)
        ts = pd.to_datetime(sdf["timestamp"], errors="coerce")

        for model_name, (kind, model_obj, feats) in models.items():
            sdf_m = sdf.dropna(subset=list(feats)).copy()
            if sdf_m.empty:
                continue
            x, _ = split_xy(sdf_m.assign(**{target_col: y_true[: len(sdf_m)]}), feats, target_col)
            if kind == "sklearn":
                y_pred = np.asarray(model_obj.predict(x), dtype=np.float32)
            else:
                import xgboost as xgb

                dmat = xgb.DMatrix(x, feature_names=list(feats))
                y_pred = np.asarray(model_obj.predict(dmat), dtype=np.float32)
            # Align to sdf_m index
            pred_full = np.full((sdf.shape[0],), np.nan, dtype=np.float32)
            pred_full[sdf_m.index.to_numpy() - sdf.index.min()] = y_pred
            preds[model_name] = pred_full

        if not preds:
            continue

        # Line plot: prediction vs actual
        plt.figure(figsize=(12, 4))
        plt.plot(ts, y_true, label="actual", linewidth=1.5)
        for model_name, y_pred in preds.items():
            plt.plot(ts, y_pred, label=model_name, linewidth=1.0, alpha=0.9)
        plt.title(f"{station} | {target_col} | Prediction vs Actual")
        plt.xlabel("timestamp")
        plt.ylabel(target_col)
        plt.legend()
        plt.tight_layout()
        plt.savefig(out_dir / f"{station}_pred_vs_actual.png", dpi=150)
        plt.close()

        # Scatter: y_pred vs y_true for each model
        for model_name, y_pred in preds.items():
            mask = np.isfinite(y_true) & np.isfinite(y_pred)
            if int(mask.sum()) < 50:
                continue
            plt.figure(figsize=(5, 5))
            plt.scatter(y_true[mask], y_pred[mask], s=8, alpha=0.4)
            lim = float(np.nanmax([np.nanmax(y_true[mask]), np.nanmax(y_pred[mask])]))
            plt.plot([0, lim], [0, lim], "r--", linewidth=1)
            plt.title(f"{station} | {model_name} | Scatter")
            plt.xlabel("actual")
            plt.ylabel("predicted")
            plt.tight_layout()
            plt.savefig(out_dir / f"{station}_{model_name}_scatter.png", dpi=150)
            plt.close()

    logging.info("Plots saved to %s", out_dir)
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except KeyboardInterrupt:
        print("Interrupted.", file=sys.stderr)
        raise
